FROM node:alpine 

RUN mkdir -p /usr/src/app/client && chown -R node:node /usr/src/app/client

WORKDIR /usr/src/app/client 

COPY package.json yarn.lock ./

USER node

RUN yarn install --pure-lockfile

COPY --chown=node:node . .

EXPOSE $REACT_PORT