#Docker swarm for deployment
version: "3.9"

services:
  mongodb:
    image: mongo
    restart: unless-stopped
    ports:
      - 27017: 27017
    volumes:
      - db:/data/db
    networks:
      - backend

  server:
    depends_on:
      - mongodb
    image: sagyam/pms-server
    restart: unless-stopped
    deploy:
      replicas: 5
    ports:
      - 5000: 5000
    networks:
      - backend
      - frontend

  client:
    depends_on:
      - server
    image: sagyam/pms-client
    restart: unless-stopped
    command: nginx -g 'daemon off;'
    deploy:
      replicas: 5

    ports:
      - 80:80
      - 443:443
    networks:
      - frontend

volumes:
  db:

networks:
  backend:
  frontend:
