version: "3.9"
services:
  mongodb:
    image: mongo
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $MONGODB_PORT:$MONGODB_PORT
    volumes:
      - db:/data/db
    networks:
      - backend

  server:
    depends_on:
      - mongodb
    build:
      context: ./server
      dockerfile: Dockerfile
      image: pms-server
    restart: unless-stopped
    env_file: ./.env
    command: yarn dev
    volumes:
      - ./server:/usr/src/app/server
    ports:
      - $NODE_PORT:$NODE_PORT

    networks:
      - backend
      - frontend

    client:
      depends_on:
        - server
      build:
        context: ./client
        dockerfile: Dockerfile.dev
        image: pms-client
      env_file: ./.env
      command: yarn start
      volumes:
        - ./client:/usr/src/app/client
      ports:
        - $REACT_PORT:$REACT_PORT
      networks:
        - frontend

volumes:
  db:

networks:
  backend:
  frontend:
